apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoind-cnf
data:
  bitcoin.conf: |
    testnet=1
    rpcallowip=0.0.0.0/0
    rpcallowip=127.0.0.1
    txindex=1
    server=1
    disablewallet=0
    
    fallbackfee=0.001
    paytxfee=0.001
    maxtxfee=1000
    mintxfee=0.00000001
    
    rpcuser=sarah
    rpcpassword=pikachutestnetB2
    
    [testnet]
    rpcbind=127.0.0.1
    rpcport=8332
